// Regenerate the declarative agent-preset patch for this bundle.
//
// dsh 0.1.7 replaced the legacy `$DSH_HOME/.agent-presets/<id>/` directory
// discovery with `@deepseek-ai/dsh-agent-preset` declaration rows carried by
// bundle patches. This script inlines preset/code-pipeline/agent.cordis.yml
// under the declaration's `config.plugins`, taking id/name/description from
// preset.yml. Run it after editing either source file:
//
//   node scripts/build-preset.mjs
//
// The generated preset/code-pipeline/cordis.patch.yml is committed; the Host
// never runs this script.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dir = join(root, 'preset', 'code-pipeline');
const id = 'code-pipeline';

/** Minimal reader for the two scalar fields preset.yml carries. */
function readScalar(text, key) {
  const match = new RegExp('^' + key + ':\\s*(.*)$', 'm').exec(text);
  if (match === null) throw new Error('preset.yml is missing "' + key + '"');
  const raw = match[1].trim();
  if (raw.length >= 2 && (raw[0] === '"' || raw[0] === "'")) return raw.slice(1, -1);
  return raw;
}

const meta = readFileSync(join(dir, 'preset.yml'), 'utf8');
const name = readScalar(meta, 'name');
const description = readScalar(meta, 'description');
const composition = readFileSync(join(dir, 'agent.cordis.yml'), 'utf8').replace(/\n+$/, '');
const indented = composition.split('\n').map((line) => (line.length === 0 ? line : '          ' + line)).join('\n');

const patch = [
  '# GENERATED by scripts/build-preset.mjs — do not edit by hand.',
  '# Source: preset/code-pipeline/{preset.yml,agent.cordis.yml}',
  '# dsh 0.1.7 preset declaration (bundle patch).',
  '- insert:',
  '    - id: preset-' + id,
  "      name: '@deepseek-ai/dsh-agent-preset'",
  '      config:',
  '        id: ' + id,
  '        name: ' + JSON.stringify(name),
  '        description: ' + JSON.stringify(description),
  '        order: 5',
  '        plugins:',
  indented,
  '',
].join('\n');

writeFileSync(join(dir, 'cordis.patch.yml'), patch);
console.log('wrote ' + join(dir, 'cordis.patch.yml') + ' (' + patch.split('\n').length + ' lines)');
